/*#	Sales Analysis Question	Business Purpose
1	What is the total sales revenue generated by RetailMart?	= Measure overall business performance
2	How does sales revenue change year-over-year (1997 vs 1998)? =	Identify sales growth or decline
3	What are the monthly sales trends across 1997 and 1998?	= Identify seasonal patterns and peak months
4	Which month generated the highest and lowest sales revenue?	= Find strongest and weakest sales periods
5	Which stores generated the highest total sales revenue?	= Compare store-level performance
6	Which stores experienced the highest sales growth from 1997 to 1998? =	Identify improving/declining stores
7	What is the average sales value per transaction?	= Measure average transaction value
8	What are the daily/weekly sales patterns and which days generate the most sales? =	Identify high-performing selling days
9. Which stores generate the highest profit?
10.Which stores have the highest profit margin?
11.Which months had the highest and lowest YoY sales growth?
12. How did the number of units sold change from 1997 to 1998?*/


#1	What is the total sales revenue generated by RetailMart?
-- YoY Growth = (1998 Sales − 1997 Sales) / 1997 Sales × 100
select round(sum(p.product_retail_price * t.quantity),2) as total_sales_revenue
from products p
join transactions t
on p.product_id = t.product_id;
/*RetailMart generated $1,764,546.44 in total sales revenue across 1997 and 1998.*/
#2	How does sales revenue change year-over-year (1997 vs 1998)?
with yearly_sale as (select year(t.transactions_date) as sales_year,
round(sum(p.product_retail_price * t.quantity),2) as total_sales_revenue
from products p
join transactions t
on p.product_id = t.product_id
group by year(t.transactions_date)
order by sales_year desc)
                             -- 1997: LAG(total_sales) = NULL because there is no previous year in our data → so no YoY growth can be calculated.
						     -- 1998: total_sales = 1998 sales (current year) and LAG(total_sales) = 1997 sales (previous year).
select sales_year,
       total_sales_revenue,
       round((total_sales_revenue - lag(total_sales_revenue) over(order by sales_year))
          / (lag(total_sales_revenue) over(order by sales_year))*100,2) as yoy_growth_percentage
from yearly_sale
order by sales_year;

/*RetailMart generated $565,238.13 in sales in 1997.
Sales increased to $1,199,308.31 in 1998.
This represents a 112.18% year-over-year growth, meaning sales more than doubled in 1998.
The absolute increase in revenue was approximately $634,070.18.
This indicates a strong improvement in RetailMart's sales performance in 1998.*/

##Question 3: What are the monthly sales trends across 1997 and 1998?
select year(t.transactions_date) as year,
       month(t.transactions_date) as months,
       round(sum(p.product_retail_price * t.quantity),2) as total_sales
from transactions t
join products p 
on t.product_id = p.product_id
group by year(t.transactions_date),
       month(t.transactions_date) 
order by year , months;
/*December was the highest-selling month in both years: $56,965.64 (1997) and $120,160.84 (1998).
October was the lowest-selling month: $42,342.27 (1997) and $92,435.91 (1998).
December 1998 sales were 110.94% higher than December 1997.
November–December showed the strongest sales performance, indicating a clear year-end sales peak.
Every month in 1998 generated higher sales than the corresponding month in 1997.*/

## 4️ Which month had the highest sales and which month had the lowest sales across 1997–1998?

WITH monthly_sales AS (
    SELECT
        YEAR(t.transactions_date) AS sales_year,
        MONTH(t.transactions_date) AS sales_month,
        ROUND(SUM(p.product_retail_price * t.quantity), 2) AS total_sales
    FROM transactions AS t
    JOIN products AS p
        ON t.product_id = p.product_id
    GROUP BY
        YEAR(t.transactions_date),
        MONTH(t.transactions_date)
), -- calculate the total sales by month
ranked_sales AS (
    SELECT
        *,
        RANK() OVER (ORDER BY total_sales DESC) AS highest_rank,
        RANK() OVER (ORDER BY total_sales ASC) AS lowest_rank
    FROM monthly_sales
) -- ranked highest and lowest sales using rank window function

SELECT
    sales_year,
    sales_month,
    total_sales,
    CASE
        WHEN highest_rank = 1 THEN 'Highest'
        WHEN lowest_rank = 1 THEN 'Lowest'          -- give the status to the ranks
    END AS sales_status    
FROM ranked_sales
WHERE highest_rank = 1
   OR lowest_rank = 1
order by sales_year desc;

/*December 1998 was RetailMart's strongest sales month, while October 1997 was the weakest.
 This suggests a significant increase in sales performance over the two-year period, with particularly strong year-end demand.*/
 
##Question 5   Which stores generated the highest total sales revenue?

-- Calculate sales for each store
select t.store_id,
       round(sum(t.quantity * p.product_retail_price) ,2) as total_sales
from transactions as t
join products as p
on t.product_id = p.product_id
group by t.store_id
order by total_sales desc;

/*Store 13 is the strongest-performing store($170,398.94), while Store 5 is the weakest ($4,903.20).
 The top two stores contribute around 18.6% of total sales (328,094.84/1,764,546.44) × 100
 indicating that sales are concentrated among a few high-performing stores.*/
 
 ## 6️ Which stores experienced the highest sales growth from 1997 to 1998?
 
with yearly_store_sales as (select t.store_id, year(transactions_date) year,
       round(sum(t.quantity * p.product_retail_price) ,2) as total_sales
from transactions as t 
join products as p
on t.product_id = p.product_id
group by t.store_id, year(transactions_date)),  -- calculate yearly store sales


store_growth AS (
    SELECT
        store_id,
        year,
        total_sales,
        LAG(total_sales) OVER (               -- define previous year sales
            PARTITION BY store_id
            ORDER BY year
        ) AS previous_year_sales
    FROM yearly_store_sales
)

SELECT store_id,
        year,
        total_sales,
        previous_year_sales,
        round(
             (
             (total_sales - previous_year_sales)
        / previous_year_sales )* 100,2) as yoy_growth_percentage
        
FROM store_growth
where year = 1998 and previous_year_sales IS NOT NULL
ORDER BY yoy_growth_percentage DESC;


/*Store 16 had the highest YoY growth at 22.60%.
Store 15 ranked second with 20.31% growth.
Store 13, despite being the highest-selling store overall, experienced a 4.63% decline in 1998.
Store 23 also declined by 4.45%.
11 out of 13 stores with comparable data experienced positive growth.
The contrast between Store 13's high revenue and negative growth shows that overall sales and sales growth should be evaluated separately.

business insight: highest sales ≠ highest growth.*/

##7️  What is the average sales value per transaction?(average revenue generated by each transaction.)
-- Average Transaction Value = Total Sales Revenue / Number of Transactions

select 
   round(sum(t.quantity * p.product_retail_price) / count(*) , 2) as avg_revenue_pertransaction
from transactions t 
join products p
on t.product_id = p.product_id;

/*RetailMart generated an average of $6.54 revenue per transaction.
This indicates that the typical transaction value is relatively small, suggesting customers generally purchase low-value baskets or a limited number of products per transaction.*/

select count(*) from transactions;

## 8. What are the daily/weekly sales patterns, and which days generate the most sales?

SELECT
    DAYNAME(t.transactions_date) AS day_name,   -- Calculate sales by day of week
    ROUND(
        SUM(t.quantity * p.product_retail_price),
        2
    ) AS total_sales
FROM transactions AS t
JOIN products AS p
    ON t.product_id = p.product_id
GROUP BY DAYNAME(t.transactions_date)
ORDER BY total_sales DESC;

/*Thursday generated the highest sales: $266,162.12.
Tuesday had the lowest sales: $234,129.83.
Thursday sales were 13.68% higher than Tuesday.
Monday was the second-highest sales day at $264,794.31.
Sales were relatively balanced across the week, with no single day dominating.*/


## 9. Which stores generate the highest profit?
-- Profit = (Retail Price - Cost Price) × Quantity
SELECT
    t.store_id,
    ROUND(
        SUM(
            (p.product_retail_price - p.product_cost) * t.quantity
        ),
        2
    ) AS total_profit
FROM transactions AS t
JOIN products AS p
    ON t.product_id = p.product_id
GROUP BY t.store_id
ORDER BY total_profit DESC;

/*Store 13 is RetailMart's strongest store in both revenue and profit, but its 4.63% YoY sales decline
 suggests that management should investigate the reason for the recent decline despite its strong profitability.*/
 
 ## 10. Which stores have the highest profit margin?
 
 -- Profit Margin % = (Total Profit / Total Sales) × 100
 
 SELECT
    t.store_id,

    ROUND(
        SUM(t.quantity * p.product_retail_price),
        2
    ) AS total_sales,

    ROUND(
        SUM(
            (p.product_retail_price - p.product_cost) * t.quantity
        ),
        2
    ) AS total_profit,

    ROUND(
        SUM(
            (p.product_retail_price - p.product_cost) * t.quantity
        )
        /
        SUM(t.quantity * p.product_retail_price)
        * 100,
        2
    ) AS profit_margin_percentage

FROM transactions AS t
JOIN products AS p
    ON t.product_id = p.product_id

GROUP BY t.store_id
ORDER BY profit_margin_percentage DESC;

/*Store 5 has the highest margin (59.87%) but the lowest sales, while Store 13 has the highest sales and profit with a 59.69% margin. 
Since margins are almost identical across stores, increasing sales volume appears to be the main driver of higher profit.*/

## 11 Which months had the highest and lowest YoY sales growth?

WITH monthly_sales AS (
    SELECT
        YEAR(t.transactions_date) AS sales_year,
        MONTH(t.transactions_date) AS sales_month,                --    calculate sales by months
        ROUND(
            SUM(p.product_retail_price * t.quantity),
            2
        ) AS total_sales
    FROM transactions AS t
    JOIN products AS p
        ON t.product_id = p.product_id
    GROUP BY
        YEAR(t.transactions_date),
        MONTH(t.transactions_date)
),

monthly_growth AS (
    SELECT
        sales_month,
        sales_year,
        total_sales,                         -- define previous year sale
        LAG(total_sales) OVER (
            PARTITION BY sales_month
            ORDER BY sales_year
        ) AS previous_year_sales
    FROM monthly_sales
)

SELECT
    sales_month,
    total_sales,
    previous_year_sales,
    ROUND(
        (total_sales - previous_year_sales)
        / previous_year_sales * 100,
        2
    ) AS yoy_growth_percentage
FROM monthly_growth
WHERE sales_year = 1998
  AND previous_year_sales IS NOT NULL
ORDER BY yoy_growth_percentage DESC;

/*September 1998 had the highest YoY growth at 131.32%.
March 1998 had the lowest YoY growth at 96.32%.
Even the lowest-growth month, March, still generated 96.32% more sales than March 1997.
All 12 months recorded more than 96% YoY growth, showing very strong and consistent growth.
September's growth was 35 percentage points higher than March.*/

/*One important distinction

Notice that December had the highest sales revenue, but September had the highest growth rate.

That's another great business-analysis point:

Highest sales ≠ highest growth.

December 1998: highest sales → $120,160.84
September 1998: highest growth → 131.32% */

## 12. How did the number of units sold change from 1997 to 1998?



WITH yearly_units AS (
    SELECT
        YEAR(t.transactions_date) AS sales_year,
        SUM(t.quantity) AS total_units_sold             -- Calculate units sold by year
    FROM transactions AS t
    GROUP BY YEAR(t.transactions_date)
),

unit_growth AS (
    SELECT
        sales_year,
        total_units_sold,                                  -- Calculate YoY unit growth
        LAG(total_units_sold) OVER (
            ORDER BY sales_year
        ) AS previous_year_units
    FROM yearly_units
)

SELECT
    sales_year,
    total_units_sold,
    previous_year_units,
    ROUND(
        (total_units_sold - previous_year_units)
        / previous_year_units * 100,
        2
    ) AS yoy_unit_growth_percentage
FROM unit_growth
WHERE sales_year = 1998
  AND previous_year_units IS NOT NULL;
  
/*Units sold increased from 266,773 in 1997 to 566,716 in 1998, representing 112.42% growth.
 However, 1998 contains substantially more transaction records than 1997, so the increase may partly reflect differences in data coverage/volume.
 Therefore, the result should be interpreted with caution when assessing actual business growth.*/
 
 